project:
  type: default
  output-dir: ../docs
  render:
    - formation.ipynb
    - trading.ipynb
    - formation_slides.qmd
    - trading_slides.qmd

format:
  html:
    theme: [darkly, custom.scss]
    toc: true
    toc-depth: 2
    toc-location: left
    toc-title: "目錄"
    smooth-scroll: true
    code-fold: show
    code-summary: "查看程式碼"
    code-copy: true
    code-line-numbers: false
    highlight-style: dracula
    html-math-method: katex
    grid:
      body-width: 860px
      sidebar-width: 270px
    self-contained: true
    anchor-sections: true
    citations-hover: false
    footnotes-hover: false
    link-external-newwindow: true

execute:
  enabled: false
  echo: true
  warning: false
