import json

notebook_path = "notebooks/strategies_logic.ipynb"

# 定義每個 cell
cells = []

# ==================== CELL 0: Title & Overview ====================
cell_0 = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 📊 S&P 500 Pairs Trading 策略交易邏輯與數學原理詳解\n",
        "\n",
        "## 📝 執行摘要與系統概述\n",
        "\n",
        "本 Jupyter Notebook 旨在**完整且詳細地整理本量化平台內的所有配對交易 (Pairs Trading) 策略交易邏輯、數學公式與核心架構**。\n",
        "配對交易是一種經典的**市場中性 (Market Neutral) 統計套利策略**，其基本假設是：若兩隻資產（或其對數組合）在歷史上存在長期的平穩走勢關聯，則當其短期走勢出現異常偏離時，價差必定會在未來收斂。此時，可以通過「買低賣高（多弱空強）」來獲取無風險的統計套利收益。\n",
        "\n",
        "本平台的核心技術架構包含三個部分：\n",
        "1. **科學化滾動視窗驗證 (Rolling Walk-Forward Backtesting)**：系統採用滾動交疊視窗設計。每一期分為**形成期 (Formation Period)**（預設 $F = 252$ 天）與**交易期 (Trading Period)**（預設 $T = 126$ 天），以 rolling step ($S = 21$ 天) 滾動往前推進。各期獨立篩選配對並進行交易，實現多週期並行的帳戶權益追蹤。\n",
        "2. **高效能並行網格搜尋引擎 (Parallelized Grid Search)**：利用 Python 多進程 (Multiprocessing) 加速，在主進程中一次性讀取價格矩陣，子進程共用記憶體數據，針對 7 組核心網格參數（Top N、Stop Loss、Z-Window、PSL、MSR、DSZ 與 VOL）進行極速搜尋。\n",
        "3. **策略庫實作 (Strategies)**：本平台目前實作了 4 種主要的配對交易策略，均存放在 `strategies/` 目錄下。本文件將對這 4 個 `.py` 檔案進行深度解析。\n",
        "\n",
        "### 🔄 單期滾動 Walk-Forward 回測流程\n",
        "\n",
        "```mermaid\n",
        "graph TD\n",
        "    A[歷史價格數據] --> B[分期切割 Windowing]\n",
        "    B --> C[形成期計算 F=252天]\n",
        "    C --> D{篩選最佳配對 Top N}\n",
        "    D --> E[交易期回測 T=126天]\n",
        "    E --> F[結算該期 PnL 並進行風控]\n",
        "    F --> G[時間軸滾動前推 Step S=21天]\n",
        "    G --> B\n",
        "```\n",
        "\n",
        "---"
    ]
}
cells.append(cell_0)

# ==================== CELL 1: Shared Quantitative Framework ====================
cell_1 = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 🧠 一、 共享核心量化架構與部位風控機制\n",
        "\n",
        "本平台所有策略均建立在一個統一的統計框架與風控系統之上。在深入個別策略之前，必須先理解這些共用的數學公式與風險控制防線。\n",
        "\n",
        "### 1.1 OLS 線性回歸 (Ordinary Least Squares)\n",
        "用於估計配對標的價格之間的長期均衡係數與對沖比例：\n",
        "$$y_t = \\alpha + \\beta \\cdot x_t + \\epsilon_t$$\n",
        "其中：\n",
        "- $y_t$ 為標的 A 的價格（或對數價格）\n",
        "- $x_t$ 為標的 B 的價格（或對數價格）\n",
        "- $\\beta$ 為避險比例 (Hedge Ratio)\n",
        "- $\\alpha$ 為均值偏離常數 (OLS Alpha)\n",
        "- $\\epsilon_t$ 為殘差序列 (Residuals)\n",
        "\n",
        "### 1.2 Engle-Granger 共整合單根檢定 (ADF Test)\n",
        "對 OLS 迴歸產生的殘差序列 $\\epsilon_t$ 執行無截距項、無時間趨勢項的簡化 Augmented Dickey-Fuller (ADF) 單根檢定，以驗證殘差是否具備平穩性 (Stationarity)：\n",
        "$$\\Delta \\epsilon_t = \\gamma \\epsilon_{t-1} + \\sum_{i=1}^p \\delta_i \\Delta \\epsilon_{t-i} + e_t$$\n",
        "- **零假設 ($H_0$)**：$\\gamma = 0$（存在單根，殘差不平穩，兩者無共整合關係）。\n",
        "- **對立假設 ($H_1$)**：$\\gamma < 0$（殘差平穩，具備共整合關係，價差會均值回歸）。\n",
        "系統同時計算正反雙向回歸（A對B 與 B對A），並**選擇 ADF p-value 較小（最顯著）的方向**作為交易方向，藉此根除因隨意指定自變量而產生的共整合判定偏差。\n",
        "\n",
        "### 1.3 誤差修正模型 (ECM) 與半衰期 (Half-Life) 估計\n",
        "為了量化價差從偏離回歸至均值中心的速度，系統對通過共整合檢定的配對建立一階誤差修正模型：\n",
        "$$\\Delta \\epsilon_t = a + \\lambda \\cdot \\epsilon_{t-1} + u_t$$\n",
        "其中 $\\lambda$ 為均值回歸速度（必須為負值才具收斂性）。均值回歸的半衰期 (Half-life) 指價差偏離減半所需的時間，計算公式為：\n",
        "$$\\text{Half-Life} = -\\frac{\\ln(2)}{\\lambda}$$\n",
        "系統僅保留半衰期在合理交易日之內的配對。若半衰期過小，可能代表高頻微幅噪聲，交易成本將蠶食利潤；若過大，則代表回歸過慢，會產生嚴重的資金佔用風險。\n",
        "\n",
        "### 1.4 Hurst 指數篩選 (Hurst Exponent)\n",
        "使用 R/S 分析近似 Hurst 指數，用以衡量序列的長程記憶性與均值回歸傾向：\n",
        "- $H = 0.5$：隨機漫步。\n",
        "- $H > 0.5$：趨勢持續性序列。\n",
        "- $H < 0.5$：反持續性（均值回歸）序列。Hurst 越小，回歸越強烈。\n",
        "系統一般設定 $\\text{Hurst} < 0.40$ 的過濾閾值，以篩選具備強均值回歸特徵的配對組合。\n",
        "\n",
        "### 1.5 六大風控與部位管理系統\n",
        "1. **個股單筆停損 (`SL`)**：當特定交易配對的未實現虧損比例達到或超過 `stop_loss_pct`（以分配給該配對的資金為分母）時，強制執行平倉：\n",
        "   $$\\text{Loss Ratio} = -\\frac{\\text{Trade PnL}}{\\text{Capital per Pair}} \\ge \\text{stop\\_loss\\_pct}$$\n",
        "   若設定不允許重新進場，該配對在該期內將永久凍結 (`is_stopped = True`)。\n",
        "2. **部位動態 Z-Score 偏離停損 (`DSZ`)**：當價差 Z-Score 絕對值偏離過大，例如 $|Z_t| > \\text{dynamic\\_stop\\_z}$（如 3.0 或 5.0）時，說明發生了結構性破裂 (Structural Break) 或極端非對稱基本面事件，系統將即刻啟動動態停損出場。\n",
        "3. **全域投資組合層級最大回撤停損 (`PSL`)**：當總資金累積每日虧損達到 `portfolio_stop_loss_pct` (如 10%) 時，觸發 PSL，**一鍵斬倉所有持倉配對**，重置所有插槽部位，並在剩餘回測期內凍結所有交易，以保護核心本金。\n",
        "4. **產業分散化集中度上限 (`MSR`)**：為了防止配對標的過度集中在某一特定產業（例如金融或科技板塊），系統設定 `max_sector_ratio` 參數。每一期單一產業選入的配對對數上限為 $\\max(1, \\lfloor N \\cdot \\text{max\\_sector\\_ratio} \\rfloor)$，實現外部高度多元化。\n",
        "5. **方向性建倉冷卻機制 (Cooldown Period)**：平倉後（不論是正常平倉或停損且允許重新進場），系統會進入冷卻狀態。\n",
        "   - 若原先為做多 (Position = 1)，則必須等到 $Z_t \\ge -\\text{EXIT\\_Z}$ 才能解除冷卻，再次評估進場。\n",
        "   - 若原先為做空 (Position = -1)，則必須等到 $Z_t \\le \\text{EXIT\\_Z}$ 才能解除冷卻。\n",
        "6. **自適應波動率調節機制 (`VOL ADJ`)**：若近期市場波動度顯著放大，系統會計算 20 日滾動價差標準差，對形成期基礎標準差進行倍數乘積放大：\n",
        "   $$\\sigma_{adjusted} = \\sigma_{formation} \\times \\max\\left(1.0, \\frac{\\sigma_{roll20}}{\\sigma_{formation}}\\right)$$\n",
        "   使 Z-Score 隨波動率自適應收縮，防止在市場無序劇烈動盪中頻繁觸發無效建倉訊號。\n",
        "\n",
        "### 1.6 核心績效評估指標\n",
        "- **最終權益值 (Final Equity)**：$\\text{Initial Capital} + \\text{Cumulative PnL}$\n",
        "- **年化報酬率 (Annualized Return, CAGR)**：幾何年化公式\n",
        "  $$\\text{Ann\\_Ret} = (1 + \\text{Cum\\_Ret})^{12 / n\\_{months}} - 1$$\n",
        "- **夏普比率 (Sharpe Ratio)**：$\\text{Sharpe} = \\sqrt{252} \\times \\frac{\\text{Mean}(R_{daily})}{\\text{Std}(R_{daily})}$$\n",
        "- **原始資金約束報酬率 (RCC)**：以初始配置總資金為分母。 $\\text{RCC} = \\frac{\\text{Final PnL}}{\\text{Initial Capital}}$\n",
        "- **實際參與資金報酬率 (REC)**：以實際發生過建倉交易的配對所佔用的總資金為分母。 \n",
        "  $$\\text{REC} = \\frac{\\text{Final PnL}}{N_{traded} \\times C_{pair}}$$\n",
        "  其中 $C_{pair} = \\text{Initial Capital} / N$ 為分配給單一配對的資金限制。此指標更能反映策略的資金實際使用效率。\n",
        "\n",
        "---"
    ]
}
cells.append(cell_1)

# ==================== CELL 2: ssd_basic.py ====================
cell_2 = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 📏 二、 經典 SSD (Basic) 距離策略\n",
        "\n",
        "### 檔案位置：`strategies/ssd_basic.py`\n",
        "\n",
        "經典 SSD (Basic) 策略基於**價格走勢歐氏距離最小化**原則，是最為傳統與直觀的配對交易策略。\n",
        "\n",
        "### 2.1 形成期邏輯 (Formation Period)\n",
        "\n",
        "#### A. 價格正規化 (Price Normalization)\n",
        "由於不同股票的絕對價格級距存在巨大差異，為了在同一維度下比對走勢，SSD 策略在**形成期第一天價格**的基準上對所有股票進行正規化：\n",
        "$$P'_{i, t} = \\frac{P_{i, t}}{P_{i, 0}}$$\n",
        "其中 $P_{i, 0}$ 為形成期第一天股票 $i$ 的收盤價。正規化後，所有股票在第一天的價格皆為 1.0。\n",
        "\n",
        "#### B. 歐氏距離平方和 (Sum of Squared Differences, SSD)\n",
        "計算形成期內所有股票兩兩之間的走勢距離平方和。為了防止非理性跨行業配對，本平台僅在相同產業板塊內進行兩兩計算：\n",
        "$$\\text{SSD}_{A,B} = \\sum_{t=1}^F (P'_{A,t} - P'_{B,t})^2$$\n",
        "其中 $F$ 為形成期的總交易日天數。SSD 數值越小，代表兩檔股票在形成期內的走勢高度趨同。系統將相同產業內的候選配對依據 SSD 升序排序，挑選前 $N$ 對最小者進入交易期。\n",
        "\n",
        "### 2.2 交易期與資金配置 (Trading & Capital Allocation)\n",
        "\n",
        "#### A. 避險比例與資金分配\n",
        "- **對沖比例固定**：在 Basic 版中，對沖比例 $\\beta$ **固定設定為 1.0**。\n",
        "- **等權重資金分配**：建倉時，分配給該對配對的資金 $C_{pair}$ 會被**均等平分**給兩隻股票，即股票 A 與股票 B 各分配到 $C_{pair} \\times 0.5$ 的市值部位：\n",
        "  $$v_a = C_{pair} \\times 0.5, \\quad v_b = C_{pair} \\times 0.5$$\n",
        "  這代表股票 A 與股票 B 的股數分別為 $v_a / P_{A,t}$ 和 $-v_b / P_{B,t}$（若為多 A 空 B）。\n",
        "\n",
        "#### B. 交易價差與 Z-Score\n",
        "- **即時價差 (Spread)**：\n",
        "  $$\\text{Spread}_t = P'_{A,t} - P'_{B,t}$$\n",
        "- **Z-Score 生成**：\n",
        "  - 若 `ZSCORE_WINDOW = 0` (固定參數模式)，則使用形成期計算出的價差均值 $\\mu_{form}$ 與標準差 $\\sigma_{form}$ 作為標準化中心：\n",
        "    $$Z_t = \\frac{\\text{Spread}_t - \\mu_{form}}{\\sigma_{form}}$$\n",
        "  - 若 `ZSCORE_WINDOW > 0` (滾動視窗模式)，則使用交易期過去 $W$ 天的滾動價差均值 $\\mu_{roll, t}$ 與滾動價差標準差 $\\sigma_{roll, t}$ 作為中心：\n",
        "    $$Z_t = \\frac{\\text{Spread}_t - \\mu_{roll, t}}{\\sigma_{roll, t}}$$"
    ]
}
cells.append(cell_2)

# ==================== CELL 3: ssd_basic.py key code ====================
cell_3 = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# strategies/ssd_basic.py 核心運算片段\n",
        "\n",
        "# 1. 形成期歐氏距離平方和 (SSD) 計算\n",
        "# 在 Formation 中使用 scipy.spatial.distance.pdist 高效計算\n",
        "# norm_vals 為 (n_tickers, F) 的正規化價格陣列\n",
        "# ssd_matrix = ssd.pdist(norm_vals, metric='sqeuclidean')\n",
        "\n",
        "# 2. 交易期價差與 Z-Score 計算 (固定 vs 滾動)\n",
        "def compute_basic_zscore(norm_p_a, norm_p_b, zscore_window, form_spread_mean, form_spread_std, min_spread_std):\n",
        "    import numpy as np\n",
        "    import pandas as pd\n",
        "    \n",
        "    if zscore_window == 0:\n",
        "        # 固定參數模式：使用形成期統計值\n",
        "        spread = norm_p_a - norm_p_b\n",
        "        safe_std = max(form_spread_std, min_spread_std)\n",
        "        zscore = (spread - form_spread_mean) / safe_std\n",
        "    else:\n",
        "        # 滾動視窗模式\n",
        "        roll_mean_a = norm_p_a.rolling(window=zscore_window).mean()\n",
        "        roll_mean_b = norm_p_b.rolling(window=zscore_window).mean()\n",
        "        roll_alpha = roll_mean_a - roll_mean_b\n",
        "        spread = norm_p_a - roll_alpha - norm_p_b\n",
        "        \n",
        "        roll_std = (norm_p_a - norm_p_b).rolling(window=zscore_window).std()\n",
        "        safe_std = np.maximum(roll_std, min_spread_std)\n",
        "        zscore = spread / safe_std\n",
        "    return zscore\n"
    ]
}
cells.append(cell_3)

# ==================== CELL 4: ssd.py ====================
cell_4 = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 📈 三、 進階 SSD (OLS) 殘差滾動策略\n",
        "\n",
        "### 檔案位置：`strategies/ssd.py`\n",
        "\n",
        "進階 SSD (OLS) 策略在經典 SSD 基礎上引入了**對數價格 Z-Score 標準化**、**動態避險比例 (OLS Beta)** 以及**高階統計量篩選過濾（共整合、半衰期與 Hurst 指數）**，是一種更為精緻的統計套利策略。\n",
        "\n",
        "### 3.1 形成期邏輯 (Formation Period)\n",
        "\n",
        "#### A. 對數價格標準化 (Log Price Z-Score Normalization)\n",
        "為了消除絕對價格階層與波動幅度的差異，進階 SSD 使用對數價格在整個形成期內的均值 $\\mu_{\\ln(P_i)}$ 與標準差 $\\sigma_{\\ln(P_i)}$ 進行標準化：\n",
        "$$P'_{i, t} = \\frac{\\ln(P_{i, t}) - \\mu_{\\ln(P_i)}}{\\sigma_{\\ln(P_i)}}$$\n",
        "所有後續的 SSD 距離、對沖比例與價差均基於此標準化對數價格 $P'_{i, t}$ 計算。\n",
        "\n",
        "#### B. 歐氏距離計算與初篩\n",
        "計算同一產業內所有股票的標準化價格距離：\n",
        "$$\\text{SSD}_{A,B} = \\sum_{t=1}^F (P'_{A,t} - P'_{B,t})^2$$\n",
        "系統先依 SSD 升序排序，挑選前 $\\text{top\\_n} \\times 15$ 組候選配對，再進行慢速的高階統計量篩選。\n",
        "\n",
        "#### C. 高階統計特徵慢速過濾\n",
        "對於初篩配對，以 OLS 估計對沖比例 $\\beta$ 並計算價差殘差 $\\epsilon_t = P'_{A,t} - \\beta \\cdot P'_{B,t}$，並進行以下三項過濾：\n",
        "1. **Engle-Granger 共整合檢定**：對殘差序列進行 ADF 單根檢定，要求 p-value 小於 0.05（顯著拒絕隨機漫步假說）。\n",
        "2. **Ornstein-Uhlenbeck 半衰期過濾**：建立殘差差分模型，估計均值回歸速度 $\\lambda$，要求半衰期 $2.0 \\le \\text{Half-Life} \\le 40.0$ 天。\n",
        "3. **Hurst 指數過濾**：計算殘差的 Hurst 指數，要求 $\\text{Hurst} < 0.40$（確認強烈均值回歸傾向）。\n",
        "最後保留通過所有檢定且 SSD 最小的前 $N$ 對。\n",
        "\n",
        "### 3.2 交易期與資金配置 (Trading & Capital Allocation)\n",
        "\n",
        "#### A. 避險比例與資金加權配置\n",
        "- **對沖比例 (Hedge Ratio)**：由形成期標準化對數價格的 OLS 迴歸斜率決定（A對B）：\n",
        "  $$\\beta = \\frac{\\text{Cov}(P'_A, P'_B)}{\\text{Var}(P'_B)}$$\n",
        "- **部位資金分配**：根據對沖比例 $\\beta$ 進行加權資金配置，以確保多空頭寸的風險對等（Beta 中性）：\n",
        "  $$\\text{Total Weight} = 1.0 + |\\beta|$$\n",
        "  $$v_a = C_{pair} \\times \\frac{1.0}{\\text{Total Weight}}, \\quad v_b = C_{pair} \\times \\frac{|\\beta|}{\\text{Total Weight}}$$\n",
        "\n",
        "#### B. 交易期 Z-Score 計算 (固定 vs 滾動)\n",
        "- 若 `ZSCORE_WINDOW = 0` (固定參數模式)，價差及 Z-Score 為：\n",
        "  $$\\text{Spread}_t = P'_{A,t} - \\beta \\cdot P'_{B,t}$$\n",
        "  $$Z_t = \\frac{\\text{Spread}_t - \\mu_{form}}{\\sigma_{form}}$$\n",
        "- 若 `ZSCORE_WINDOW > 0` (滾動視窗模式)，則在過去 $W$ 天的對數價格上動態滾動重新估計 $\\alpha_t, \\beta_t$：\n",
        "  $$\\beta_t = \\frac{\\text{Cov}_W(P'_A, P'_B)}{\\text{Var}_W(P'_B)}, \\quad \\alpha_t = \\text{Mean}_W(P'_A) - \\beta_t \\cdot \\text{Mean}_W(P'_B)$$\n",
        "  即時價差：\n",
        "  $$\\text{Spread}_t = P'_{A,t} - \\alpha_t - \\beta_t \\cdot P'_{B,t}$$\n",
        "  價差標準差使用滾動 OLS 殘差標準差估計：\n",
        "  $$\\sigma_{residual, t} = \\sqrt{\\max\\left(\\text{Var}_W(P'_A) - \\beta_t \\cdot \\text{Cov}_W(P'_A, P'_B), 0\\right)}$$\n",
        "  $$Z_t = \\frac{\\text{Spread}_t}{\\sigma_{residual, t}}$$"
    ]
}
cells.append(cell_4)

# ==================== CELL 5: ssd.py key code ====================
cell_5 = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# strategies/ssd.py 核心統計過濾與動態 Z-Score 計算\n",
        "\n",
        "# 1. OLS 斜率 (Beta) 與殘差\n",
        "def compute_ols_beta_and_residual(y, x):\n",
        "    import numpy as np\n",
        "    cov_xy = np.cov(x, y)[0, 1]\n",
        "    var_x = np.var(x, ddof=1)\n",
        "    beta = cov_xy / var_x if var_x > 1e-8 else 0.0\n",
        "    residual = y - beta * x\n",
        "    return beta, residual\n",
        "\n",
        "# 2. Ornstein-Uhlenbeck 半衰期計算\n",
        "def compute_half_life(spread):\n",
        "    import numpy as np\n",
        "    dy = np.diff(spread)\n",
        "    y_lag = spread[:-1]\n",
        "    n_dy = len(dy)\n",
        "    x_mat = np.column_stack([np.ones(n_dy), y_lag])\n",
        "    try:\n",
        "        coeffs, _, _, _ = np.linalg.lstsq(x_mat, dy, rcond=None)\n",
        "        lambda_val = coeffs[1]\n",
        "    except Exception:\n",
        "        lambda_val = 0.0\n",
        "    if lambda_val >= 0.0:\n",
        "        return -1.0 # 代表不收斂\n",
        "    return -np.log(2) / lambda_val\n",
        "\n",
        "# 3. 交易期滾動 OLS 殘差 Z-Score 估計\n",
        "def compute_rolling_ols_zscore(norm_p_a, norm_p_b, w, min_spread_std):\n",
        "    import numpy as np\n",
        "    import pandas as pd\n",
        "    \n",
        "    # 滾動共變異數與變異數\n",
        "    roll_cov = norm_p_b.rolling(window=w).cov(norm_p_a)\n",
        "    roll_var = norm_p_b.rolling(window=w).var()\n",
        "    roll_beta = np.where(roll_var > 1e-8, roll_cov / roll_var, 0.0)\n",
        "    roll_beta = pd.Series(roll_beta, index=norm_p_a.index)\n",
        "    \n",
        "    # 滾動均值\n",
        "    roll_mean_a = norm_p_a.rolling(window=w).mean()\n",
        "    roll_mean_b = norm_p_b.rolling(window=w).mean()\n",
        "    roll_alpha = roll_mean_a - roll_beta * roll_mean_b\n",
        "    \n",
        "    # 即時價差\n",
        "    spread = norm_p_a - roll_alpha - roll_beta * norm_p_b\n",
        "    \n",
        "    # 滾動殘差標準差 (基於 R^2 關係計算)\n",
        "    roll_var_a = norm_p_a.rolling(window=w).var()\n",
        "    roll_res_var = roll_var_a - roll_beta * roll_cov\n",
        "    roll_std = np.sqrt(np.maximum(roll_res_var, 0.0))\n",
        "    safe_std = np.maximum(roll_std, min_spread_std)\n",
        "    \n",
        "    zscore = spread / safe_std\n",
        "    return zscore, roll_beta\n"
    ]
}
cells.append(cell_5)

# ==================== CELL 6: HDBSCAN.py ====================
cell_6 = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 🌐 四、 HDBSCAN + UMAP/PCA 密度分群策略\n",
        "\n",
        "### 檔案位置：`strategies/HDBSCAN.py`\n",
        "\n",
        "HDBSCAN 策略擺脫了兩兩配對暴力歐氏距離計算的限制，採用**特徵空間聚類**的思想，先提取每隻股票的多維時序統計特徵，進行降維後以密度分群演算法 (HDBSCAN) 進行自動聚類，並只在同一個分群內篩選最顯著共整合的配對。這是一種極具現代感的量化機器學習策略。\n",
        "\n",
        "### 4.1 形成期邏輯 (Formation Period)\n",
        "\n",
        "#### A. 多維金融特徵萃取 (Feature Extraction)\n",
        "系統支援兩種特徵模式 (`stats13` 或 `path`)：\n",
        "- **`stats13` 模式**：對每檔股票的對數價格收益率序列提取 13 維特徵：\n",
        "  1. **動量類 (4維)**：5日、21日、63日、126日對數收益率。\n",
        "  2. **波動率類 (3維)**：21日、63日滾動報酬率標準差，及全期報酬率標準差。\n",
        "  3. **自相關類 (3維)**：報酬率的一階、五階、二十一階自相關係數 (Lag-1, Lag-5, Lag-21 Autocorrelation)。\n",
        "  4. **統計矩類 (3維)**：偏態 (Skewness)、峰態 (Kurtosis)、及 Hurst 指數近似值。\n",
        "- **`path` 模式**：直接使用形成期標準化後的對數價格路徑本身作為特徵向量（維度等於形成期天數 $F$）。\n",
        "\n",
        "#### B. UMAP / PCA 降維 (Dimensionality Reduction)\n",
        "為了克服高維特徵空間中的「維度災難」(Curse of Dimensionality) 且便於密度聚類，系統使用 **UMAP (Uniform Manifold Approximation and Projection)**（或備用的 PCA）將 13 維特徵（或 $F$ 維路徑）降維至指定的低維空間（預設為 5 維）。\n",
        "\n",
        "#### C. HDBSCAN 密度聚類 (Density-Based Clustering)\n",
        "在每個產業分組內，對降維後的低維特徵嵌入進行 HDBSCAN 聚類：\n",
        "- 自動尋找任意形狀的密度群落，不需要像 K-Means 般預設分群數。\n",
        "- 能夠識別並自動過濾無法歸類的「噪音點」 ($label = -1$)，不參與後續配對，大幅降低錯誤配對的機率。\n",
        "\n",
        "#### D. 同產業 × 同群落 雙重篩選與共整合檢定\n",
        "篩選條件：**同一產業板塊，且被 HDBSCAN 劃分到同一個群落的股票**，才能兩兩成對進行 Engle-Granger 共整合檢定與 OLS 回歸擬合：\n",
        "$$\\ln(P_{A,t}) = \\alpha + \\beta \\cdot \\ln(P_{B,t}) + \\epsilon_t$$\n",
        "系統計算雙向回歸，選取 ADF p-value 較小的方向，並以 `adf_pvalue_threshold`（預設 0.05，保守為 0.01）進行過濾。同時套用半衰期與 Hurst 指數過濾，最後挑選 ADF 統計量最小的前 $N$ 對配對。\n",
        "\n",
        "### 🧠 HDBSCAN + Engle-Granger 選股流程\n",
        "\n",
        "```mermaid\n",
        "graph TD\n",
        "    A[股票歷史對數價格] --> B[特徵提取: stats13 或 path]\n",
        "    B --> C[UMAP/PCA 降維]\n",
        "    C --> D[HDBSCAN 密度聚類]\n",
        "    D --> E[去除雜訊點: label=-1]\n",
        "    D --> F[同產業 x 同群落雙重篩選]\n",
        "    F --> G[Engle-Granger OLS 擬合]\n",
        "    G --> H[ADF 共整合檢定 p < 0.05]\n",
        "    H --> I[Ornstein-Uhlenbeck 半衰期過濾]\n",
        "    I --> J[Hurst 指數過濾 < 0.40]\n",
        "    J --> K[選取 ADF 統計量最小的前 N 對]\n",
        "```\n",
        "\n",
        "### 4.2 交易期與資金配置 (Trading & Capital Allocation)\n",
        "\n",
        "#### A. 資金分配\n",
        "與進階 OLS SSD 策略一致，根據 Engle-Granger OLS 回歸斜率 $\\beta$ 進行加權資金配置，實現 Beta 風險中性：\n",
        "$$\\text{Total Weight} = 1.0 + |\\beta|$$\n",
        "$$v_a = C_{pair} \\times \\frac{1.0}{\\text{Total Weight}}, \\quad v_b = C_{pair} \\times \\frac{|\\beta|}{\\text{Total Weight}}$$\n",
        "\n",
        "#### B. 交易期 Z-Score 計算 (對數空間)\n",
        "不同於 SSD 策略是在正規化價格空間，HDBSCAN 策略是在**對數價格空間**上計算 Spread：\n",
        "- 若 `ZSCORE_WINDOW = 0`：\n",
        "  $$\\text{Spread}_t = \\ln(P_{A,t}) - \\alpha - \\beta \\cdot \\ln(P_{B,t})$$\n",
        "  $$Z_t = \\frac{\\text{Spread}_t - \\mu_{form}}{\\sigma_{form}}$$\n",
        "- 若 `ZSCORE_WINDOW > 0`：\n",
        "  在交易期滾動視窗 $W$ 內動態重新進行 $\\ln(P_A)$ 對 $\\ln(P_B)$ 的 OLS 迴歸得到動態 $\\alpha_t, \\beta_t$。價差及 Z-Score 計算與 `ssd.py` 的對數版本相同。"
    ]
}
cells.append(cell_6)

# ==================== CELL 7: HDBSCAN.py key code ====================
cell_7 = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# strategies/HDBSCAN.py 核心特徵萃取與聚類流程\n",
        "\n",
        "# 1. 13維金融統計特徵萃取\n",
        "def extract_stats13_features(log_price):\n",
        "    import numpy as np\n",
        "    import pandas as pd\n",
        "    \n",
        "    ret = np.diff(log_price)\n",
        "    n = len(ret)\n",
        "    \n",
        "    # 5, 21, 63, 126日 動量 (對數回報率)\n",
        "    m5 = float(log_price[-1] - log_price[-5]) if n >= 5 else 0.0\n",
        "    m21 = float(log_price[-1] - log_price[-21]) if n >= 21 else 0.0\n",
        "    m63 = float(log_price[-1] - log_price[-63]) if n >= 63 else 0.0\n",
        "    m126 = float(log_price[-1] - log_price[-126]) if n >= 126 else 0.0\n",
        "    \n",
        "    # 波動率特徵\n",
        "    v21 = float(np.std(ret[-21:], ddof=1)) if n >= 21 else 0.0\n",
        "    v63 = float(np.std(ret[-63:], ddof=1)) if n >= 63 else 0.0\n",
        "    v_all = float(np.std(ret, ddof=1)) if n > 1 else 0.0\n",
        "    \n",
        "    # 自相關特徵 (Lag-1, 5, 21)\n",
        "    def get_autocorr(lag):\n",
        "        if n <= lag: return 0.0\n",
        "        x1, x2 = ret[:-lag], ret[lag:]\n",
        "        try: return float(np.corrcoef(x1, x2)[0, 1])\n",
        "        except: return 0.0\n",
        "        \n",
        "    a1, a5, a21 = get_autocorr(1), get_autocorr(5), get_autocorr(21)\n",
        "    \n",
        "    # 統計矩\n",
        "    skew = float(pd.Series(ret).skew()) if n > 2 else 0.0\n",
        "    kurt = float(pd.Series(ret).kurt()) if n > 3 else 0.0\n",
        "    \n",
        "    # Hurst 近似值\n",
        "    h_approx = 0.5\n",
        "    \n",
        "    features = np.array([m5, m21, m63, m126, v21, v63, v_all, a1, a5, a21, skew, kurt, h_approx])\n",
        "    return np.where(np.isfinite(features), features, 0.0)\n",
        "\n",
        "# 2. HDBSCAN 密度聚類實作\n",
        "def run_hdbscan_clustering(X, min_cluster_size=3, min_samples=1):\n",
        "    import hdbscan\n",
        "    clusterer = hdbscan.HDBSCAN(\n",
        "        min_cluster_size=min_cluster_size,\n",
        "        min_samples=min_samples,\n",
        "        metric='euclidean'\n",
        "    )\n",
        "    labels = clusterer.fit_predict(X)\n",
        "    return labels\n"
    ]
}
cells.append(cell_7)

# ==================== CELL 8: HDBSCAN_MultiFactor.py ====================
cell_8 = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 📊 五、 HDBSCAN 金融多因子特徵空間策略\n",
        "\n",
        "### 檔案位置：`strategies/HDBSCAN_MultiFactor.py`\n",
        "\n",
        "HDBSCAN 多因子策略是密度分群策略的變體。其核心思想是：不採用純時序統計指標或路徑作為分群特徵，而是使用**金融學與計量經濟學中具備強大學術根基的 6 大穩健因子**來構建特徵空間，並且**跳過 UMAP 降維步驟**直接進行聚類。\n",
        "\n",
        "### 5.1 形成期邏輯 (Formation Period)\n",
        "\n",
        "#### A. 6 大穩健金融因子特徵空間\n",
        "在形成期內，系統對每隻股票提取以下 6 個核心維度的特徵：\n",
        "1. **市場貝他 (Market Beta, $\\beta_M$)**：評估個股對於市場組合（由所有個股等權重報酬組成）的系統性風險敏感度：\n",
        "   $$\\beta_M = \\frac{\\text{Cov}(R_{i}, R_M)}{\\text{Var}(R_M)}$$\n",
        "   其中 $R_M$ 是形成期內全市場個股報酬的平均序列。\n",
        "2. **全期收益波動率 (Volatility, $\\sigma$)**：個股日對數報酬率的標準差，捕捉個股的整體風險層級。\n",
        "3. **報酬偏態 (Skewness)**：反映收益率分佈的非對稱性，代表極端極值風險。\n",
        "4. **報酬峰態 (Kurtosis)**：反映收益率分佈的肥尾特徵，捕捉厚尾極端風險。\n",
        "5. **長期趨勢斜率 (Trend Slope)**：對對數價格序列相對於時間序列 $t = 1, 2, \\dots, F$ 進行線性 OLS 擬合所得的斜率，用以度量中期價格趨勢的方向。\n",
        "6. **特異波動率 (Idiosyncratic Volatility, $\\sigma_{idio}$)**：將個股日報酬率對市場組合報酬率進行線性回歸，剔除市場系統性變動後，其殘差（特異性收益）的標準差：\n",
        "   $$R_{i,t} = \\alpha_i + \\beta_{M,i} \\cdot R_{M,t} + \\eta_{i,t}$$\n",
        "   $$\\sigma_{idio} = \\sqrt{\\text{Var}(\\eta_i)}$$\n",
        "   這代表個股無法被市場風險所解釋的獨特資產波動度。\n",
        "\n",
        "#### B. 免降維直接分群\n",
        "由於上述 6 大因子維度適中（僅有 6 維）且每個維度皆具備極為明確且互不相同的經濟意義，**此策略跳過了 UMAP 降維步驟**。特徵經 Z-Score 標準化後，直接在 6 維金融因子空間上執行 HDBSCAN 聚類，這極大保留了特徵的原始金融解釋性，避免降維過程中的信息丟失。\n",
        "\n",
        "#### C. 其餘共整合檢定與交易機制\n",
        "同產業 $\\times$ 同群落雙重篩選、Engle-Granger 共整合檢定、半衰期/Hurst過濾、避險比例加權資金配置，以及交易期固定/滾動 Z-Score 與部位管理，**均與 `HDBSCAN.py` 策略完全一致**。\n",
        "\n",
        "---"
    ]
}
cells.append(cell_8)

# ==================== CELL 9: HDBSCAN_MultiFactor.py key code ====================
cell_9 = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# strategies/HDBSCAN_MultiFactor.py 6大金融因子特徵建構\n",
        "\n",
        "def build_6factor_features(log_prices, returns_df):\n",
        "    import numpy as np\n",
        "    import pandas as pd\n",
        "    \n",
        "    tickers = log_prices.columns.tolist()\n",
        "    market_returns = returns_df.mean(axis=1).values\n",
        "    t_indices = np.arange(len(log_prices))\n",
        "    feat_rows = []\n",
        "    \n",
        "    for ticker in tickers:\n",
        "        prices = log_prices[ticker].values\n",
        "        ticker_ret = returns_df[ticker].values\n",
        "        \n",
        "        # 1. Market Beta\n",
        "        cov_mat = np.cov(ticker_ret, market_returns)\n",
        "        beta = cov_mat[0, 1] / cov_mat[1, 1] if cov_mat[1, 1] > 1e-12 else 0.0\n",
        "        \n",
        "        # 2. Total Volatility\n",
        "        vol = np.std(ticker_ret, ddof=1) if len(ticker_ret) > 1 else 0.0\n",
        "        \n",
        "        # 3. Skewness\n",
        "        skew = float(pd.Series(ticker_ret).skew())\n",
        "        \n",
        "        # 4. Kurtosis\n",
        "        kurt = float(pd.Series(ticker_ret).kurt())\n",
        "        \n",
        "        # 5. Trend Slope (對數價格對時間 OLS 斜率)\n",
        "        x_mat = np.column_stack([np.ones(len(prices)), t_indices])\n",
        "        coeffs, _, _, _ = np.linalg.lstsq(x_mat, prices, rcond=None)\n",
        "        slope = float(coeffs[1])\n",
        "        \n",
        "        # 6. Idiosyncratic Volatility (特異波動率)\n",
        "        n_len = len(ticker_ret)\n",
        "        market_mat = np.column_stack([np.ones(n_len), market_returns])\n",
        "        coeffs_m, _, _, _ = np.linalg.lstsq(market_mat, ticker_ret, rcond=None)\n",
        "        resid = ticker_ret - coeffs_m[0] - coeffs_m[1] * market_returns\n",
        "        idio_vol = np.std(resid, ddof=1) if len(resid) > 1 else vol\n",
        "        \n",
        "        feats = np.array([beta, vol, skew, kurt, slope, idio_vol])\n",
        "        feat_rows.append(np.where(np.isfinite(feats), feats, 0.0))\n",
        "        \n",
        "    return feat_rows\n"
    ]
}
cells.append(cell_9)

# ==================== CELL 10: Comparison Table ====================
cell_10 = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 📊 六、 四大策略核心特徵與參數對比總結\n",
        "\n",
        "為了方便選擇最適合的策略，下表整理並對比了這 4 個策略的完整核心細項：\n",
        "\n",
        "| 策略特徵 | 經典 SSD (Basic) | 進階 SSD (OLS) | HDBSCAN 聚類 | HDBSCAN 時序多因子 |\n",
        "| :--- | :--- | :--- | :--- | :--- |\n",
        "| **對應檔案** | `ssd_basic.py` | `ssd.py` | `HDBSCAN.py` | `HDBSCAN_MultiFactor.py` |\n",
        "| **正規化空間** | 原始價格除以首日價格 | 對數價格 Z-Score 標準化 | 對數價格 Z-Score 標準化 | 對數價格 Z-Score 標準化 |\n",
        "| **距離/分群維度** | 形成期價格長度 $F$ | 形成期價格長度 $F$ | 13維時序特徵 / 降維至 5維 | 6維金融時序特徵 / 無降維 |\n",
        "| **配對初篩標準** | 同產業內走勢歐氏距離平方和最小 | 同產業內走勢歐氏距離平方和最小 | 同產業且同 HDBSCAN 密度分群內 | 同產業且同 HDBSCAN 密度分群內 |\n",
        "| **避險比例 $\\beta$** | 固定為 1.0 | 形成期對數價格 OLS 斜率 | 形成期對數價格 OLS 斜率 | 形成期對數價格 OLS 斜率 |\n",
        "| **統計檢定過濾** | 無 | EG共整合、半衰期、Hurst 指數 | EG共整合、半衰期、Hurst 指數 | EG共整合、半衰期、Hurst 指數 |\n",
        "| **資金配置方式** | 兩檔股票 50% / 50% 等權重 | 依 OLS $\\beta$ 風險中性比例分配 | 依 OLS $\\beta$ 風險中性比例分配 | 依 OLS $\\beta$ 風險中性比例分配 |\n",
        "| **滾動 Z-Score** | 滾動價差均值與標準差 | 滾動 OLS 斜率、常數與殘差標準差 | 滾動 OLS 斜率、常數與殘差標準差 | 滾動 OLS 斜率、常數與殘差標準差 |\n",
        "| **適應波動度調節** | 支援 | 支援 | 支援 | 支援 |\n",
        "| **產業集中度上限** | 支援 | 支援 | 支援（多層級，含群落上限） | 支援（多層級，含群落上限） |\n",
        "\n",
        "### 💡 結論與實務建議\n",
        "1. **經典 SSD (`ssd_basic.py`)**：架構最簡單，由於避險比例固定為 1.0，只適合走勢完全平行且價格級距一致的極度同質標的。\n",
        "2. **進階 SSD (`ssd.py`)**：在對數與 OLS 空間下進行距離計算，並引入共整合與半衰期過濾，效能相較 Basic 版有顯著提升，是經典的距離套利模型。\n",
        "3. **HDBSCAN 密度分群 (`HDBSCAN.py`)**：透過機器學習降維與密度分群，能先篩選出具備相似「波動、趨勢與結構特徵」的股票群落，從根本上提高了配對的經濟合理性，並排除了無法分類的雜訊標的。\n",
        "4. **HDBSCAN 多因子 (`HDBSCAN_MultiFactor.py`)**：改以金融學術界公認的 6 大穩健因子（如市場 Beta、特異波動率等）作為特徵空間，免降維聚類，提供了最強的金融學解釋性與抗過擬合 (Overfitting) 能力。\n",
        "\n",
        "---"
    ]
}
cells.append(cell_10)

# 寫入檔案
ipynb_content = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (ipykernel)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.11.5"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(ipynb_content, f, ensure_ascii=False, indent=2)

print("SUCCESS")
